-- SPDX-License-Identifier: MIT
-- stats.lua --- progress tracking and spaced repetition from scores
-- Copyright (c) 2026 Jakob Kastelic

-- DESCRIPTION
--      stats.lua reads SCORE lines from standard input and maintains a
--      persistent log of performance. It calculates daily total scores,
--      accumulates daily and per-lesson practice duration, monitors a
--      daily "goal streak," and applies the SM-2 algorithm (Spaced
--      Repetition System) to individual lessons.
--
-- ARGUMENTS
--      arg[1]: Path to the stats storage file (e.g., "my_progress.lua").
--              This file is a standard Lua script that returns a table.
--              If it doesn't exist, a new one will be created.
--
-- INPUT FORMAT
--      The program expects lines in the format generated by score.lua:
--      SCORE time=<t> lesson=<id> accuracy=<n> score=<n.nn> duration=<s.sss> ...
--
-- OUTPUT FORMAT
--      For every valid SCORE line processed, the program writes to stdout:
--      STATS time=<t> total_today=<n.nn> total_duration_today=<s.sss> streak=<n>
--            lesson=<id>[ivl=<n>,ease=<n.nn>,tot_dur=<s.sss>,n_pass=<n>,n_fail=<n>,...]

local DEFAULT_SCORE_GOAL = 1000
local stats_file = arg[1]

if not stats_file then
	io.write("Usage: lua stats.lua <stats_file.lua>\n")
	os.exit(1)
end

-------------------------------------------------------------------------------
-- DATA PERSISTENCE
-------------------------------------------------------------------------------

local function load_stats(path)
	local f = io.open(path, "r")
	if not f then
		return {
			score_goal = DEFAULT_SCORE_GOAL,
			daily = {},
			lessons = {},
		}
	end
	f:close()

	local chunk, err = loadfile(path)
	if not chunk then
		io.stderr:write("Error: Could not parse stats file: " .. tostring(err) .. "\n")
		os.exit(1)
	end

	local data = chunk()
	if type(data) ~= "table" or not data.lessons then
		io.stderr:write("Error: Stats file is not in a recognized format.\n")
		os.exit(1)
	end

	data.daily = data.daily or {}
	return data
end

local function save_stats(path, data)
	local f = io.open(path, "w")
	if not f then
		io.stderr:write("Error: Could not write to stats file.\n")
		os.exit(1)
	end

	local function serialize(t, indent, depth)
		depth = depth or 0
		local s = "{\n"
		local next_indent = indent .. "  "

		-- Sort keys for consistent file output
		local keys = {}
		for k in pairs(t) do
			table.insert(keys, k)
		end
		table.sort(keys, function(a, b)
			return tostring(a) < tostring(b)
		end)

		for _, k in ipairs(keys) do
			local v = t[k]
			s = s .. next_indent .. "[" .. (type(k) == "string" and string.format("%q", k) or k) .. "] = "

			if type(v) == "table" then
				-- Special handling: Put daily records on one line
				if depth == 1 and (v.score or v.duration) then
					s = s .. '{["score"] = ' .. v.score .. ', ["duration"] = ' .. v.duration .. "},\n"
				else
					s = s .. serialize(v, next_indent, depth + 1) .. ",\n"
				end
			elseif type(v) == "string" then
				s = s .. string.format("%q", v) .. ",\n"
			else
				s = s .. tostring(v) .. ",\n"
			end
		end
		return s .. indent .. "}"
	end

	f:write("return " .. serialize(data, "", 0) .. "\n")
	f:flush()
	f:close()
end

-------------------------------------------------------------------------------
-- CORE LOGIC
-------------------------------------------------------------------------------

local function get_date_str()
	return os.date("%Y-%m-%d")
end

local function calculate_streak(data)
	local streak = 0
	local current_ts = os.time()

	while true do
		local d_str = os.date("%Y-%m-%d", current_ts)
		local day_data = data.daily[d_str]
		local day_score = day_data and day_data.score or 0

		if day_score >= data.score_goal then
			streak = streak + 1
			current_ts = current_ts - 86400
		else
			if d_str == get_date_str() and streak == 0 then
				current_ts = current_ts - 86400
			else
				break
			end
		end
	end
	return streak
end

local function update_anki(l_data, success, duration)
	l_data.n_pass = l_data.n_pass or 0
	l_data.n_fail = l_data.n_fail or 0
	l_data.n_pass_tot = l_data.n_pass_tot or 0
	l_data.n_fail_tot = l_data.n_fail_tot or 0
	l_data.ivl = l_data.ivl or 0
	l_data.ease = l_data.ease or 2.5
	l_data.total_duration = (l_data.total_duration or 0) + duration

	if success then
		l_data.n_pass = l_data.n_pass + 1
		l_data.n_fail = 0
		l_data.n_pass_tot = l_data.n_pass_tot + 1

		if l_data.n_pass == 1 then
			l_data.ivl = 1
		elseif l_data.n_pass == 2 then
			l_data.ivl = 6
		else
			l_data.ivl = math.ceil(l_data.ivl * l_data.ease)
		end
		l_data.ease = l_data.ease + 0.1
	else
		l_data.n_fail = l_data.n_fail + 1
		l_data.n_pass = 0
		l_data.n_fail_tot = l_data.n_fail_tot + 1
		l_data.ivl = 1
		l_data.ease = math.max(1.3, l_data.ease - 0.2)
	end

	l_data.last_date = get_date_str()
end

-------------------------------------------------------------------------------
-- COMMANDS
-------------------------------------------------------------------------------

local function handle_query_stats(stats, line)
	local today = get_date_str()
	local today_data = stats.daily[today]
	local total_today = today_data and today_data.score or 0
	local total_dur_today = today_data and today_data.duration or 0
	local streak = calculate_streak(stats)

	io.write(
		string.format(
			"STATS time=%d total_today=%.2f goal=%.2f total_duration_today=%.3f streak=%d\n",
			os.time(),
			total_today,
			stats.score_goal,
			total_dur_today,
			streak
		)
	)
end

local function handle_load_lesson(stats, line)
	local l_id = line:match("LOAD_LESSON (%S+)")
	if not l_id then
		return
	end

	local today = get_date_str()
	local today_data = stats.daily[today]
	local total_today = today_data and today_data.score or 0
	local total_dur_today = today_data and today_data.duration or 0
	local streak = calculate_streak(stats)
	local l = stats.lessons[l_id]

	io.write(
		string.format(
			"STATS total_today=%.2f goal=%.2f total_duration_today=%.3f streak=%d lesson=%s[ivl=%d,ease=%.2f,tot_dur=%.3f,n_pass=%d,n_fail=%d,n_pass_tot=%d,n_fail_tot=%d]\n",
			stats.daily[today].score,
			stats.score_goal,
			stats.daily[today].duration,
			streak,
			l_id,
			l.ivl,
			l.ease,
			l.total_duration,
			l.n_pass,
			l.n_fail,
			l.n_pass_tot,
			l.n_fail_tot
		)
	)
end

local function handle_score(stats, line)
	local time, l_id, acc, score, dur =
		line:match("SCORE time=(%S+) lesson=(%S+) accuracy=(%S+) score=(%S+) duration=(%S+)")

	if not (time and l_id and score and dur) then
		return
	end

	local today = get_date_str()
	local score_val = tonumber(score)
	local acc_val = tonumber(acc)
	local dur_val = tonumber(dur)
	local lesson_time = tonumber(time)

	stats.daily[today] = stats.daily[today] or { score = 0, duration = 0 }
	stats.daily[today].score = stats.daily[today].score + score_val
	stats.daily[today].duration = stats.daily[today].duration + dur_val

	stats.lessons[l_id] = stats.lessons[l_id] or {}
	update_anki(stats.lessons[l_id], acc_val == 100, dur_val)

	save_stats(stats_file, stats)

	local streak = calculate_streak(stats)
	local l = stats.lessons[l_id]

	io.write(
		string.format(
			"STATS time=%d total_today=%.2f goal=%.2f total_duration_today=%.3f streak=%d lesson=%s[ivl=%d,ease=%.2f,tot_dur=%.3f,n_pass=%d,n_fail=%d,n_pass_tot=%d,n_fail_tot=%d]\n",
			lesson_time,
			stats.daily[today].score,
			stats.score_goal,
			stats.daily[today].duration,
			streak,
			l_id,
			l.ivl,
			l.ease,
			l.total_duration,
			l.n_pass,
			l.n_fail,
			l.n_pass_tot,
			l.n_fail_tot
		)
	)
end

-------------------------------------------------------------------------------
-- MAIN EXECUTION
-------------------------------------------------------------------------------

for line in io.lines() do
	local stats = load_stats(stats_file)

	if line:match("^QUERY_STATS") then
		handle_query_stats(stats, line)
	end

	if line:match("^LOAD_LESSON") then
		handle_load_lesson(stats, line)
	end

	if line:match("^SCORE") then
		handle_score(stats, line)
	end

	save_stats(stats_file, stats)
end
