-- SPDX-License-Identifier: MIT
-- stats.lua --- progress tracking and spaced repetition from scores
-- Copyright (c) 2026 Jakob Kastelic

-- DESCRIPTION
--      stats.lua reads SCORE lines from standard input and maintains a
--      persistent log of performance. It calculates Mastery (the player's
--      demonstrated peak capability) and Power (current operational strength
--      based on memory decay). Points are awarded based on increases in
--      Mastery and Power, rewarding growth and maintenance over mindless
--      repetition of mastered material.
--
--      Mastery growth is gated by a session quality score:
--
--        quality = ema_pass * speed_factor * evenness_factor
--
--      ema_pass    : exponential moving average of pass/fail over ~10 sessions
--                    (alpha=0.18). A master plays it right almost every time.
--      speed_factor: average note time this session relative to the lesson's
--                    personal best. Faster = higher. Capped at 1.0.
--      evenness_factor: fastest/slowest note ratio. Perfect even tempo = 1.0;
--                    large spread = closer to 0. A master plays in even tempo.
--
--      Mastery only grows when accuracy >= 80% and the raw score exceeds the
--      current mastery. The growth step is scaled by quality, so high mastery
--      requires consistent, fast, and even performance across many sessions.
--
-- ARGUMENTS
--      arg[1]: Path to the stats storage file (e.g., "stats.log").
--              This file is a standard Lua script that returns a table.
--              If it doesn't exist, a new one will be created.
--
-- INPUT FORMAT
--      The program expects lines in the format generated by score.lua:
--      SCORE time=<t> lesson=<id> accuracy=<n> score=<n.nn> duration=<s.sss>
--            slowest=<s> fastest=<s> average=<s> groups=<n>
--
-- OUTPUT FORMAT
--      For every valid SCORE line processed, the program writes to stdout:
--      STATS time=<t> total_today=<n.nn> goal=<n.nn> total_duration_today=<s.sss> streak=<n>
--            lesson=<id>[ivl=<n>,ease=<n.nn>,tot_dur=<s.sss>,n_pass_tot=<n>,n_fail_tot=<n>,
--                        mastery=<n.nn>,power=<n.nn>]
--
--      mastery and power are normalized to [0,100] relative to the lesson's
--      theoretical maximum score (max_groups * 5.0). Raw values are used
--      internally for all point calculations so harder lessons remain worth more.

-- Algorithm parameter defaults. These are written into the stats log under the
-- "algorithm" key on first run (or whenever a key is absent), so they can be
-- tuned by editing the log file directly without touching this source.
local ALGORITHM_DEFAULTS = {
	score_goal = 1000, -- daily point target
	ema_alpha = 0.18, -- EMA smoothing for pass-rate (~10-session window)
	pass_accuracy = 80, -- minimum accuracy % to count as a pass
	mastery_growth = 0.20, -- fraction of (score - mastery) gap closed per session
	power_half_life = 0.693, -- ln(2): power reaches 50% of mastery at days_elapsed == ivl
	power_points_ratio = 0.5, -- power-delta weight relative to mastery-delta (1:1)
	bottleneck_thresh = 0.6, -- factor value below which it is considered a bottleneck
	dominance_margin = 0.2, -- how much lower the bottleneck must be than the others
	min_quality = 0.1, -- quality below this triggers a "raise quality" suggestion
	mastery_score_frac = 0.9, -- score must be >= this fraction of mastery to say "already mastered"
	max_consecutive = 5, -- consecutive attempts before "try_another_lesson"
	weak_ema_thresh = 0.8, -- ema_pass below this marks a lesson as "needs_work"
	ease_initial = 2.5, -- starting ease factor for new lessons
	ease_min = 1.3, -- minimum ease factor
	ease_max = 3.5, -- maximum ease factor
	ease_pass_delta = 0.1, -- ease increase on a perfect pass
	ease_fail_delta = 0.2, -- ease decrease on a fail
	ivl_first = 1, -- interval (days) after first perfect pass
	ivl_second = 6, -- interval (days) after second consecutive perfect pass
}

local stats_file = arg[1]

if not stats_file then
	io.write("Usage: lua stats.lua <stats_file.lua>\n")
	os.exit(1)
end

-------------------------------------------------------------------------------
-- UTILITIES & METRICS
-------------------------------------------------------------------------------

local function get_date_str()
	return os.date("%Y-%m-%d")
end

-- Power represents current "readiness." It is the portion of Mastery
-- currently accessible based on the SRS interval and time since last practice.
local function calculate_power(l_data, alg)
	local mastery = l_data.mastery or 0
	local ivl = l_data.ivl or 0
	local last_date = l_data.last_date

	if not last_date or ivl <= 0 then
		return 0
	end

	local y, m, d = last_date:match("(%d+)-(%d+)-(%d+)")
	local last_ts = os.time({ year = y, month = m, day = d, hour = 12 })
	local days_elapsed = math.floor(os.difftime(os.time(), last_ts) / 86400)

	-- Power reaches 50% of Mastery when days_elapsed == ivl
	local stability = math.exp(-alg.power_half_life * (math.max(0, days_elapsed) / ivl))
	return math.min(mastery, mastery * stability)
end

local function calculate_streak(data)
	local streak = 0
	local current_ts = os.time()
	local today = get_date_str()

	while true do
		local d_str = os.date("%Y-%m-%d", current_ts)
		local day_score = (data.daily[d_str] and data.daily[d_str].score) or 0
		if day_score >= data.algorithm.score_goal then
			streak = streak + 1
			current_ts = current_ts - 86400
		else
			if d_str == today and streak == 0 then
				current_ts = current_ts - 86400
			else
				break
			end
		end
	end
	return streak
end

-- Normalize a raw mastery/power value to [0,100] relative to the lesson's
-- theoretical maximum score (max_groups * 5.0, where 5.0 is the best possible
-- speed_factor). Falls back to the raw value if max_groups is not yet known.
local function normalize(raw, l_data)
	local max_groups = l_data.max_groups or 0
	if max_groups <= 0 then
		return raw
	end
	return (raw / (max_groups * 5.0)) * 100.0
end

-------------------------------------------------------------------------------
-- DATA PERSISTENCE
-------------------------------------------------------------------------------

local function load_stats(path)
	local function with_defaults(data)
		data.algorithm = data.algorithm or {}
		for k, v in pairs(ALGORITHM_DEFAULTS) do
			if data.algorithm[k] == nil then
				data.algorithm[k] = v
			end
		end
		data.daily = data.daily or {}
		data.lessons = data.lessons or {}
		return data
	end

	local f = io.open(path, "r")
	if not f then
		return with_defaults({})
	end
	f:close()
	local chunk = loadfile(path)
	if not chunk then
		return with_defaults({})
	end
	return with_defaults(chunk())
end

local function save_stats(path, data)
	local f = io.open(path, "w")
	if not f then
		return
	end
	local function serialize(t, indent, depth)
		depth = depth or 0
		local s = "{\n"
		local next_indent = indent .. "  "
		local keys = {}
		for k in pairs(t) do
			table.insert(keys, k)
		end
		table.sort(keys, function(a, b)
			return tostring(a) < tostring(b)
		end)
		for _, k in ipairs(keys) do
			local v = t[k]
			s = s .. next_indent .. "[" .. (type(k) == "string" and string.format("%q", k) or k) .. "] = "
			if type(v) == "table" then
				if depth == 1 and (v.score or v.duration) then
					s = s .. '{["score"] = ' .. (v.score or 0) .. ', ["duration"] = ' .. (v.duration or 0) .. "},\n"
				else
					s = s .. serialize(v, next_indent, depth + 1) .. ",\n"
				end
			elseif type(v) == "string" then
				s = s .. string.format("%q", v) .. ",\n"
			else
				s = s .. tostring(v) .. ",\n"
			end
		end
		return s .. indent .. "}"
	end
	f:write("return " .. serialize(data, "", 0) .. "\n")
	f:close()
end

-------------------------------------------------------------------------------
-- OUTPUT HELPER
-------------------------------------------------------------------------------

local function print_stats_line(stats, l_id, timestamp, suggestion)
	local alg = stats.algorithm
	local today = get_date_str()
	local d = stats.daily[today] or { score = 0, duration = 0 }
	local streak = calculate_streak(stats)

	-- Using %.0f for timestamp to avoid integer representation errors in Lua 5.3+
	local output = string.format(
		"STATS time=%.0f total_today=%.2f goal=%.2f total_duration_today=%.3f streak=%d",
		timestamp or os.time(),
		d.score,
		alg.score_goal,
		d.duration,
		streak
	)

	if l_id and stats.lessons[l_id] then
		local l = stats.lessons[l_id]
		local power = calculate_power(l, alg)
		output = output
			.. string.format(
				" lesson=%s[ivl=%d,ease=%.2f,tot_dur=%.3f,n_pass_tot=%d,n_fail_tot=%d,mastery=%.2f,power=%.2f]",
				l_id,
				math.tointeger(math.floor(l.ivl or 0)) or 0,
				l.ease or alg.ease_initial,
				l.total_duration or 0,
				math.tointeger(l.n_pass_tot or 0) or 0,
				math.tointeger(l.n_fail_tot or 0) or 0,
				normalize(l.mastery or 0, l),
				normalize(power, l)
			)
	end
	if suggestion then
		output = output .. " suggestion=" .. suggestion
	end
	io.write(output .. "\n")
end

-------------------------------------------------------------------------------
-- COMMAND HANDLERS
-------------------------------------------------------------------------------

local function handle_score(stats, line)
	local alg = stats.algorithm
	local ts, l_id, acc, score, dur =
		line:match("SCORE time=(%S+) lesson=(%S+) accuracy=(%S+) score=(%S+) duration=(%S+)")

	if not (l_id and score) or l_id == "nil" then
		return
	end
	local s_val, a_val, d_val = tonumber(score) or 0, tonumber(acc) or 0, tonumber(dur) or 0
	local today = get_date_str()

	local l = stats.lessons[l_id]
		or { ease = alg.ease_initial, ivl = 0, mastery = 0, total_duration = 0, max_groups = 0 }

	-- Update the theoretical score ceiling: groups * 5.0 (max speed_factor).
	-- Take the max across sessions in case a lesson is ever edited.
	local groups = tonumber(line:match("groups=(%d+)")) or 0
	if groups > (l.max_groups or 0) then
		l.max_groups = groups
	end

	-- 1. Snapshot raw state before update for points calculation.
	--    Points always use raw values so harder lessons give more points.
	local old_mastery = l.mastery or 0
	local old_power = calculate_power(l, alg)

	-- 2. Parse timing fields from the SCORE line.
	local slowest = tonumber(line:match("slowest=(%S+)")) or 0
	local fastest = tonumber(line:match("fastest=(%S+)")) or 0
	local average = tonumber(line:match("average=(%S+)")) or 0

	-- 2a. Update EMA of pass rate (~10-session window, alpha=ema_alpha).
	--     A pass requires accuracy >= pass_accuracy%. This is the primary consistency signal.
	local pass_this_session = (a_val >= alg.pass_accuracy) and 1.0 or 0.0
	l.ema_pass = l.ema_pass and (alg.ema_alpha * pass_this_session + (1 - alg.ema_alpha) * l.ema_pass)
		or pass_this_session

	-- 2b. Speed factor: how fast is this session relative to the lesson's personal
	--     best average note time? Lower average = faster = better.
	--     best_avg tracks the fastest (lowest) average ever recorded.
	if average > 0 then
		if not l.best_avg or average < l.best_avg then
			l.best_avg = average
		end
	end
	local speed_factor
	if average > 0 and l.best_avg and l.best_avg > 0 then
		-- Ratio of best to current: 1.0 when matching PB, decays toward 0 when slow.
		-- Clamp to [0,1] so a fluke fast session never inflates above 1.
		speed_factor = math.min(1.0, l.best_avg / average)
	else
		speed_factor = 0.0
	end

	-- 2c. Evenness factor: fastest/slowest ratio. Perfect evenness = 1.0.
	--     A wide spread between the fastest and slowest note indicates uneven tempo.
	local evenness_factor
	if slowest > 0 and fastest > 0 then
		evenness_factor = math.min(1.0, fastest / slowest)
	else
		evenness_factor = 0.0
	end

	-- 2d. Combined quality gates mastery growth. All three dimensions must be
	--     strong for mastery to advance meaningfully.
	local quality = l.ema_pass * speed_factor * evenness_factor

	-- 2f. Track consecutive attempts on this lesson (resets when another lesson
	--     is scored). Used to detect over-drilling.
	if alg.last_lesson_scored ~= l_id then
		l.n_consecutive = 1
	else
		l.n_consecutive = (l.n_consecutive or 0) + 1
	end
	alg.last_lesson_scored = l_id

	-- 2e. Derive a suggestion: call out the single clearest bottleneck, if any.
	--     Only fired when accuracy >= pass_accuracy% (otherwise it's simply "try again").
	--     A factor is considered the bottleneck when it is below bottleneck_thresh AND at
	--     least dominance_margin lower than both other factors — i.e. clearly the odd one out.
	local suggestion = nil
	if a_val < alg.pass_accuracy then
		suggestion = "try_again"
	else
		local factors = {
			{ name = "be_more_consistent", val = l.ema_pass },
			{ name = "play_faster", val = speed_factor },
			{ name = "play_more_evenly", val = evenness_factor },
		}
		local min_val = math.huge
		local min_idx = nil
		for i, f in ipairs(factors) do
			if f.val < min_val then
				min_val = f.val
				min_idx = i
			end
		end
		if min_idx and min_val < alg.bottleneck_thresh then
			local is_dominant = true
			for i, f in ipairs(factors) do
				if i ~= min_idx and (f.val - min_val) < alg.dominance_margin then
					is_dominant = false
					break
				end
			end
			if is_dominant then
				suggestion = factors[min_idx].name
			end
		end

		-- Secondary suggestions for the "good attempt, no mastery gain" cases.
		if suggestion == nil then
			if s_val <= old_mastery then
				-- Only say "already mastered" if this was a strong attempt that genuinely
				-- ran into the ceiling (score >= mastery_score_frac of mastery).
				-- A weak score that happens to be below mastery is not praise-worthy.
				if old_mastery > 0 and s_val >= old_mastery * alg.mastery_score_frac then
					suggestion = "already_mastered"
				end
			elseif quality < alg.min_quality then
				-- Score beat mastery but quality was so low it produced no real gain.
				-- Point to the weakest quality factor so they know what to work on.
				local weakest = "be_more_consistent"
				local wval = l.ema_pass
				if speed_factor < wval then
					weakest = "play_faster"
					wval = speed_factor
				end
				if evenness_factor < wval then
					weakest = "play_more_evenly"
				end
				suggestion = "raise_quality_" .. weakest
			end
		end
	end

	-- Over-drilling check: overrides everything — rest is more important.
	if l.n_consecutive >= alg.max_consecutive then
		suggestion = "try_another_lesson"
	end

	-- 3. Update Mastery: grow toward the session score, scaled by quality.
	--     Requires accuracy >= pass_accuracy% and a score that beats current mastery.
	if a_val >= alg.pass_accuracy and s_val > old_mastery then
		l.mastery = old_mastery + (s_val - old_mastery) * alg.mastery_growth * quality
	end

	-- 4. Update SRS fields
	if a_val == 100 then
		l.n_pass = (l.n_pass or 0) + 1
		l.n_fail = 0
		l.n_pass_tot = (l.n_pass_tot or 0) + 1
		if l.n_pass == 1 then
			l.ivl = alg.ivl_first
		elseif l.n_pass == 2 then
			l.ivl = alg.ivl_second
		else
			l.ivl = math.ceil((l.ivl or 1) * (l.ease or alg.ease_initial))
		end
		l.ease = math.min(alg.ease_max, (l.ease or alg.ease_initial) + alg.ease_pass_delta)
	else
		l.n_fail = (l.n_fail or 0) + 1
		l.n_pass = 0
		l.n_fail_tot = (l.n_fail_tot or 0) + 1
		l.ivl = 1
		l.ease = math.max(alg.ease_min, (l.ease or alg.ease_initial) - alg.ease_fail_delta)
	end

	l.total_duration = (l.total_duration or 0) + d_val
	l.last_date = today
	stats.lessons[l_id] = l

	-- 5. Calculate Growth Points using raw deltas (not normalized).
	--    This preserves the property that harder lessons (higher max_groups)
	--    yield more points for the same proportional improvement.
	local new_power = calculate_power(l, alg)
	local m_delta = math.max(0, (l.mastery or 0) - old_mastery)
	local p_delta = math.max(0, new_power - old_power)

	-- Mastery increases provide 1:1 points; Power increases provide power_points_ratio:1
	local points_earned = m_delta + (p_delta * alg.power_points_ratio)

	-- 6. Update Daily Totals
	stats.daily[today] = stats.daily[today] or { score = 0, duration = 0 }
	stats.daily[today].score = stats.daily[today].score + points_earned
	stats.daily[today].duration = stats.daily[today].duration + d_val

	save_stats(stats_file, stats)
	print_stats_line(stats, l_id, tonumber(ts), suggestion)
end

local function handle_suggest(stats)
	local alg = stats.algorithm
	-- 1. Discover all lesson IDs that have a seq/N.txt file.
	local available = {}
	local i = 1
	while true do
		local f = io.open("seq/" .. i .. ".txt", "r")
		if not f then
			break
		end
		f:close()
		table.insert(available, tostring(i))
		i = i + 1
	end

	if #available == 0 then
		io.write("SUGGESTION none reason=no_lessons_available\n")
		return
	end

	-- 2. Split into known (have a stats entry with mastery data) and new.
	local known = {}
	local new_lessons = {}
	for _, id in ipairs(available) do
		local l = stats.lessons[id]
		if l and (l.mastery or 0) > 0 then
			table.insert(known, id)
		else
			table.insert(new_lessons, id)
		end
	end

	-- 3. Among known lessons, find the best candidate to review.
	--    Priority 1: overdue (days_elapsed >= ivl), ranked by overdue ratio descending.
	--    Priority 2: not yet overdue but ema_pass < weak_ema_thresh (still needs work),
	--                ranked by ema_pass ascending (weakest first).
	local best_id = nil
	local best_score = -math.huge
	local best_type = nil -- "overdue" or "needs_work"

	for _, id in ipairs(known) do
		local l = stats.lessons[id]
		local ivl = l.ivl or 0
		local last_date = l.last_date
		local days_elapsed = 0
		if last_date then
			local y, m, d = last_date:match("(%d+)-(%d+)-(%d+)")
			local last_ts = os.time({ year = y, month = m, day = d, hour = 12 })
			days_elapsed = math.floor(os.difftime(os.time(), last_ts) / 86400)
		end

		if ivl > 0 and days_elapsed >= ivl then
			-- Overdue: score = days_elapsed / ivl (higher = more overdue)
			local score = days_elapsed / ivl
			if best_type ~= "overdue" or score > best_score then
				best_type = "overdue"
				best_score = score
				best_id = id
			end
		elseif best_type ~= "overdue" then
			-- Not overdue: consider if ema_pass is weak
			local ep = l.ema_pass or 0
			if ep < alg.weak_ema_thresh then
				-- Score = 1 - ema_pass so weakest gets highest score
				local score = 1.0 - ep
				if score > best_score then
					best_score = score
					best_id = id
				end
			end
		end
	end

	if best_id then
		local reason = (best_type == "overdue") and "overdue" or "needs_work"
		io.write("SUGGESTION lesson=" .. best_id .. " reason=" .. reason .. "\n")
		return
	end

	-- 4. No good known candidate — suggest the first new lesson.
	if #new_lessons > 0 then
		io.write("SUGGESTION lesson=" .. new_lessons[1] .. " reason=new_lesson\n")
		return
	end

	-- 5. All known lessons are on schedule and nothing new to learn.
	io.write("SUGGESTION none reason=all_up_to_date\n")
end

-------------------------------------------------------------------------------
-- MAIN LOOP
-------------------------------------------------------------------------------

for line in io.lines() do
	local stats = load_stats(stats_file)
	if line:match("^QUERY_STATS") then
		print_stats_line(stats)
	elseif line:match("^LOAD_LESSON") then
		print_stats_line(stats, line:match("LOAD_LESSON (%S+)"))
	elseif line:match("^SCORE") then
		handle_score(stats, line)
	elseif line:match("^SUGGEST_LESSON") then
		handle_suggest(stats)
	end
end
