/**
 * @file notes.h
 * @brief Note manupulation routines.
 * @author Jakob Kastelic
 */

#ifndef NOTES_H
#define NOTES_H

#include <stddef.h>

enum midi_note {
   NOTES_C0 = 12,
   NOTES_Cs0,
   NOTES_D0,
   NOTES_Ds0,
   NOTES_E0,
   NOTES_F0,
   NOTES_Fs0,
   NOTES_G0,
   NOTES_Gs0,
   NOTES_A0,
   NOTES_As0,
   NOTES_B0,
   NOTES_C1,
   NOTES_Cs1,
   NOTES_D1,
   NOTES_Ds1,
   NOTES_E1,
   NOTES_F1,
   NOTES_Fs1,
   NOTES_G1,
   NOTES_Gs1,
   NOTES_A1,
   NOTES_As1,
   NOTES_B1,
   NOTES_C2,
   NOTES_Cs2,
   NOTES_D2,
   NOTES_Ds2,
   NOTES_E2,
   NOTES_F2,
   NOTES_Fs2,
   NOTES_G2,
   NOTES_Gs2,
   NOTES_A2,
   NOTES_As2,
   NOTES_B2,
   NOTES_C3,
   NOTES_Cs3,
   NOTES_D3,
   NOTES_Ds3,
   NOTES_E3,
   NOTES_F3,
   NOTES_Fs3,
   NOTES_G3,
   NOTES_Gs3,
   NOTES_A3,
   NOTES_As3,
   NOTES_B3,
   NOTES_C4,
   NOTES_Cs4,
   NOTES_D4,
   NOTES_Ds4,
   NOTES_E4,
   NOTES_F4,
   NOTES_Fs4,
   NOTES_G4,
   NOTES_Gs4,
   NOTES_A4,
   NOTES_As4,
   NOTES_B4,
   NOTES_C5,
   NOTES_Cs5,
   NOTES_D5,
   NOTES_Ds5,
   NOTES_E5,
   NOTES_F5,
   NOTES_Fs5,
   NOTES_G5,
   NOTES_Gs5,
   NOTES_A5,
   NOTES_As5,
   NOTES_B5,
   NOTES_C6,
   NOTES_Cs6,
   NOTES_D6,
   NOTES_Ds6,
   NOTES_E6,
   NOTES_F6,
   NOTES_Fs6,
   NOTES_G6,
   NOTES_Gs6,
   NOTES_A6,
   NOTES_As6,
   NOTES_B6,
   NOTES_C7,
   NOTES_Cs7,
   NOTES_D7,
   NOTES_Ds7,
   NOTES_E7,
   NOTES_F7,
   NOTES_Fs7,
   NOTES_G7,
   NOTES_Gs7,
   NOTES_A7,
   NOTES_As7,
   NOTES_B7,
   NOTES_C8
};

void notes_staff(void);

void notes_dots(const enum midi_note *n_arr, size_t count);

#endif /* NOTES_H */
